# Generated by Django 5.2.10 on 2026-03-12 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('tx_id', models.CharField(max_length=255, unique=True)),
                ('token_type', models.CharField(max_length=10)),
                ('amount', models.BigIntegerField()),
                ('receipt_token', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
                'unique_together': {('user', 'resource_type', 'resource_id')},
            },
        ),
    ]
