# Generated by Django 5.2.10 on 2026-02-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('show_reminder', 'Show Reminder'), ('show_cancelled', 'Show Cancelled'), ('guest_request', 'Guest Request'), ('guest_accepted', 'Guest Accepted'), ('guest_declined', 'Guest Declined'), ('co_host_added', 'Co-Host Added')], max_length=20),
        ),
    ]
