# Generated by Django 5.2.10 on 2026-02-28 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTMPDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('twitch', 'Twitch'), ('twitter', 'X / Twitter'), ('kick', 'Kick'), ('rumble', 'Rumble'), ('custom', 'Custom')], max_length=20)),
                ('stream_key', models.CharField(help_text='Stream key (kept server-side)', max_length=500)),
                ('rtmp_url', models.CharField(blank=True, help_text='RTMP ingest URL (auto-filled per platform, editable for custom)', max_length=500)),
                ('label', models.CharField(blank=True, help_text="Friendly label, e.g. 'My YouTube Channel'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this destination is currently enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtmp_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_rtmpd_user_id_8ae552_idx')],
            },
        ),
    ]
