# Generated by Django 5.2.10 on 2026-02-28 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rtmpdestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='broadcast_days',
            field=models.JSONField(blank=True, default=list, help_text='List of day indices (0=Mon, 6=Sun) for scheduled broadcasts'),
        ),
        migrations.AddField(
            model_name='user',
            name='broadcast_time',
            field=models.TimeField(blank=True, help_text='Daily broadcast start time', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='broadcast_timezone',
            field=models.CharField(blank=True, default='UTC', help_text="Timezone for broadcast schedule (e.g. 'America/New_York')", max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('stx_address', models.CharField(blank=True, help_text='Stacks address used for payment', max_length=100)),
                ('stx_tx_id', models.CharField(blank=True, help_text='Last payment transaction ID', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='users_subsc_user_id_877733_idx')],
            },
        ),
    ]
