# Generated by Django 5.2.10 on 2026-02-28 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_broadcast_days_user_broadcast_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcpe_playlist_name', models.CharField(db_index=True, help_text='Exact playlist name as it appears in DCPE', max_length=255)),
                ('label', models.CharField(blank=True, help_text='Friendly display name (optional, shows DCPE name if empty)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dcpe_playlist_name'],
                'unique_together': {('user', 'dcpe_playlist_name')},
            },
        ),
    ]
