# Generated by Django 5.2.10 on 2026-03-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_creatorplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dm_paygate_enabled',
            field=models.BooleanField(default=False, help_text='If True, require x402 payment to send a DM to this creator'),
        ),
        migrations.AddField(
            model_name='user',
            name='dm_price_stx',
            field=models.BigIntegerField(default=0, help_text='Price in microSTX to send a DM'),
        ),
        migrations.AddField(
            model_name='user',
            name='dm_price_usdcx',
            field=models.BigIntegerField(default=0, help_text='Price in micro-USDCx to send a DM'),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_stx_address',
            field=models.CharField(blank=True, help_text='STX address for receiving payments (tips, merch). Falls back to stacks_address.', max_length=255),
        ),
    ]
