# Generated by Django 5.2.12 on 2026-03-18 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_dm_paygate_enabled_user_dm_price_stx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dapp_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DappPointEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('tip_sent', 'Tip Sent'), ('tip_received', 'Tip Received'), ('subscription_upgrade', 'Subscription Upgrade'), ('merch_purchase', 'Merch Purchase'), ('wallet_signup', 'Wallet Signup Bonus')], max_length=30)),
                ('points', models.IntegerField()),
                ('tx_id', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_dappp_user_id_f30d1c_idx')],
            },
        ),
    ]
