# Generated by Django 5.2.10 on 2026-02-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_remove_event_comment_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled_instances',
            field=models.JSONField(blank=True, default=list, help_text='List of ISO date strings for cancelled recurring event instances'),
        ),
        migrations.AddField(
            model_name='event',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week for SPECIFIC_DAY recurring events (0=Monday, 6=Sunday)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('SPECIFIC_DAY', 'Specific Day'), ('DAILY', 'Daily'), ('WEEKDAYS', 'Weekdays (Mon-Fri)'), ('WEEKENDS', 'Weekends (Sat-Sun)')], help_text='Type of recurrence pattern', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Time of day for the recurring event', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='share_count',
            field=models.IntegerField(default=0, help_text='Number of times this event has been shared'),
        ),
    ]
