# Generated by Django 5.2.10 on 2026-02-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_cancelled_instances_event_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Required for one-off events, optional for recurring', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Required for one-off events, optional for recurring', null=True),
        ),
    ]
