# Generated by Django 5.2.10 on 2026-03-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_end_datetime_alter_event_start_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
