# Generated by Django 6.0.3 on 2026-03-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('events', '0007_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='communities.community'),
        ),
    ]
