# Generated by Django 5.2.10 on 2026-03-12 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField()),
                ('price_stx', models.DecimalField(decimal_places=6, help_text='Price in STX (microstacks)', max_digits=20)),
                ('price_usdcx', models.DecimalField(decimal_places=6, help_text='Price in USDCx', max_digits=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='merch/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='merch_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Merch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tx_id', models.CharField(help_text='Stacks transaction ID', max_length=255, unique=True)),
                ('payment_currency', models.CharField(choices=[('STX', 'STX'), ('USDCx', 'USDCx')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=6, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Transfer'), ('paid', 'Paid/Verified'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('failed', 'Failed/Refunded')], default='pending', max_length=20)),
                ('shipping_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='merch.merch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merch_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
