# Generated by Django 5.2.10 on 2026-03-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_note',
            field=models.TextField(blank=True, help_text='Optional message from buyer to creator'),
        ),
    ]
