# Generated by Django 5.2.10 on 2026-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_order_buyer_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_currency',
            field=models.CharField(blank=True, choices=[('STX', 'STX'), ('USDCx', 'USDCx'), ('sBTC', 'sBTC')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tx_id',
            field=models.CharField(blank=True, default='', help_text='Stacks transaction ID', max_length=255),
        ),
    ]
