# Generated by Django - Custom migration for like/comment counts

from django.db import migrations, models


def add_fields_if_not_exist(apps, schema_editor):
    """Add fields only if they don't exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if columns exist
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='shows_show' 
            AND column_name IN ('like_count', 'comment_count')
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
        
        # Add like_count if it doesn't exist
        if 'like_count' not in existing_columns:
            cursor.execute("""
                ALTER TABLE shows_show 
                ADD COLUMN like_count INTEGER DEFAULT 0 NOT NULL
            """)
            print("✅ Added like_count column")
        else:
            print("ℹ️  like_count column already exists")
        
        # Add comment_count if it doesn't exist  
        if 'comment_count' not in existing_columns:
            cursor.execute("""
                ALTER TABLE shows_show 
                ADD COLUMN comment_count INTEGER DEFAULT 0 NOT NULL
            """)
            print("✅ Added comment_count column")
        else:
            print("ℹ️  comment_count column already exists")


def populate_counts(apps, schema_editor):
    """Populate like_count and comment_count from existing data"""
    Show = apps.get_model('shows', 'Show')
    Like = apps.get_model('users', 'Like')
    Comment = apps.get_model('users', 'Comment')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Get ContentType for Show
    try:
        show_content_type = ContentType.objects.get(app_label='shows', model='show')
    except ContentType.DoesNotExist:
        print("⚠️ Show ContentType not found, skipping count population")
        return
    
    updated_count = 0
    for show in Show.objects.all():
        # Count existing likes using content_type_id (not content_type object)
        like_count = Like.objects.filter(
            content_type_id=show_content_type.id,
            object_id=show.id
        ).count()
        
        # Count existing comments using content_type_id (not content_type object)
        comment_count = Comment.objects.filter(
            content_type_id=show_content_type.id,
            object_id=show.id
        ).count()
        
        # Update the show
        show.like_count = like_count
        show.comment_count = comment_count
        show.save(update_fields=['like_count', 'comment_count'])
        updated_count += 1
        
        print(f"✅ {show.title}: {like_count} likes, {comment_count} comments")
    
    print(f"✅ Updated counts for {updated_count} shows")


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_show_share_count_alter_show_slug_and_more'),
        ('users', '0001_initial'),  # Ensure users app is migrated
        ('contenttypes', '0002_remove_content_type_name'),  # Ensure ContentType is available
    ]

    operations = [
        # Add fields using raw SQL that checks for existence
        migrations.RunPython(add_fields_if_not_exist, reverse_code=migrations.RunPython.noop),
        # Populate counts from existing data
        migrations.RunPython(populate_counts, reverse_code=migrations.RunPython.noop),
    ]
