# Generated by Django 5.2.10 on 2026-02-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_show_share_count_alter_show_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='comment_count',
            field=models.IntegerField(default=0, help_text='Number of comments (cached)'),
        ),
        migrations.AddField(
            model_name='show',
            name='like_count',
            field=models.IntegerField(default=0, help_text='Number of likes (cached)'),
        ),
    ]
