# Generated by Django - Populate preset tags

from django.db import migrations
from django.utils.text import slugify


def create_preset_tags(apps, schema_editor):
    """Create preset tags for shows"""
    Tag = apps.get_model('shows', 'Tag')
    
    # Preset tags
    preset_tags = [
        'News & Politics',
        'Technology',
        'Entertainment',
        'Sports',
        'Comedy',
        'Education',
        'Gaming',
        'Music',
        'Science',
        'Business',
        'Health & Fitness',
        'Art & Design',
        'Food & Cooking',
        'Travel',
        'Lifestyle',
    ]
    
    created_count = 0
    for tag_name in preset_tags:
        tag, created = Tag.objects.get_or_create(
            name=tag_name,
            defaults={'slug': slugify(tag_name)}
        )
        if created:
            created_count += 1
            print(f"✅ Created tag: {tag_name}")
        else:
            print(f"ℹ️  Tag already exists: {tag_name}")
    
    print(f"✅ Created {created_count} new tags, {len(preset_tags) - created_count} already existed")


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_add_count_fields'),
    ]

    operations = [
        migrations.RunPython(create_preset_tags, reverse_code=migrations.RunPython.noop),
    ]
