# Generated by Django 5.2.10 on 2026-02-10 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_remove_show_comment_count_remove_show_like_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Optional message from the requester', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='showepisode',
            options={'ordering': ['-air_date', '-episode_number']},
        ),
        migrations.RemoveIndex(
            model_name='showepisode',
            name='shows_showe_show_id_aa71b1_idx',
        ),
        migrations.RemoveField(
            model_name='showepisode',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='show',
            name='guests',
            field=models.ManyToManyField(blank=True, help_text='Creators appearing as guests on this show', limit_choices_to={'role': 'creator'}, related_name='guest_on_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='showepisode',
            name='air_date',
            field=models.DateField(help_text='Date this episode aired'),
        ),
        migrations.AlterField(
            model_name='showepisode',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the episode', null=True),
        ),
        migrations.AlterField(
            model_name='showepisode',
            name='episode_number',
            field=models.IntegerField(help_text='Episode number for this show'),
        ),
        migrations.AlterField(
            model_name='showepisode',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to recorded episode (YouTube, etc.)'),
        ),
        migrations.AddIndex(
            model_name='showepisode',
            index=models.Index(fields=['show', '-air_date'], name='shows_showe_show_id_00128c_idx'),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='requester',
            field=models.ForeignKey(help_text='Creator requesting to be a guest', limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_guest_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guestrequest',
            name='show',
            field=models.ForeignKey(help_text='Show that the guest request is for', on_delete=django.db.models.deletion.CASCADE, related_name='guest_requests', to='shows.show'),
        ),
        migrations.AddIndex(
            model_name='guestrequest',
            index=models.Index(fields=['show', 'status'], name='shows_guest_show_id_c09643_idx'),
        ),
        migrations.AddIndex(
            model_name='guestrequest',
            index=models.Index(fields=['requester', 'status'], name='shows_guest_request_e904d8_idx'),
        ),
        migrations.AddIndex(
            model_name='guestrequest',
            index=models.Index(fields=['-created_at'], name='shows_guest_created_4fd6db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guestrequest',
            unique_together={('show', 'requester')},
        ),
    ]
