# Generated by Django 5.2.10 on 2026-02-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0009_show_comment_count_show_like_count'),
        ('shows', '0010_populate_tags'),
    ]

    operations = [
    ]
