# Generated by Django 5.2.10 on 2026-02-22 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0010_guestrequest_alter_showepisode_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='co_hosts',
            field=models.ManyToManyField(blank=True, help_text='Co-hosts who share this show on their profile', related_name='co_hosted_shows', to=settings.AUTH_USER_MODEL),
        ),
    ]
