# Generated by Django 5.2.10 on 2026-03-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0011_show_co_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='showepisode',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='showepisode',
            name='price_stx',
            field=models.BigIntegerField(default=0, help_text='Price in microSTX'),
        ),
        migrations.AddField(
            model_name='showepisode',
            name='price_usdcx',
            field=models.BigIntegerField(default=0, help_text='Price in smallest USDCx unit'),
        ),
    ]
