# Generated by Django 6.0.3 on 2026-03-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('shows', '0012_showepisode_is_premium_showepisode_price_stx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='communities.community'),
        ),
    ]
